Algoritmo "soma0"
// 
//  
// Descrição   : Faça o mesmo que antes, porém, ao invés de ler 10 números, o programa deverá ler e somar números até que o valor digitado seja zero ( 0 ).
// Autor(a)    : Victor Leinad
// Data atual  : 16/08/2021
Var

num,result:inteiro

Inicio
repita
escreval("Digite um valor:")
leia(num)
result<- num+result
escreval("O valor da soma é: ",result)
ate (num=0)


Fimalgoritmo