algoritmo "Volei"
// Função :
// Autor :
// Data : 23/08/2021
// Seção de Declarações 
var

num,cont,result,alt:inteiro

inicio

escreval("Digite o tanto de jogadores que vai ser inscrito::")
leia(num)
para cont de 1 ate num faca
escreval("Digite a altura do jogador:")
leia(alt)
result<- alt+result
fimpara
escreval("A altura media dos seus jogardores é de: ",result," metros")
fimalgoritmo
